#!/bin/sh
mkdir -p /mnt/usb
uci del_list fstab.@mount[0] >/dev/null 2>&1
uci batch <<CONF
set automount.@global[0]='global'
set automount.@global[0].enabled='1'
set automount.@global[0].timeout='3'
set automount.@global[0].mount_prefix='/mnt'
set automount.@global[0].usbfs='1'
set automount.@global[0].options='rw,sync'
set fstab.@mount[-1]='mount'
set fstab.@mount[-1].enabled='1'
set fstab.@mount[-1].device='*'
set fstab.@mount[-1].target='/mnt/usb'
set fstab.@mount[-1].fstype='auto'
set fstab.@mount[-1].options='defaults'
set fstab.@mount[-1].enabled_fsck='0'
CONF
uci commit automount
uci commit fstab
/etc/init.d/fstab enable
/etc/init.d/automount enable
exit 0
